on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    permissions: write-all
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: 'Linux-x64'
            os: ubuntu-latest

          - name: 'macOS-x64'
            arch: x86-64
            os: macos-12

          - name: 'macOS-arm64'
            arch: arm64
            os: macos-12

    env:
      SC_PATH: ${{ github.workspace }}/supercollider
      INSTALL_PATH: ${{ github.workspace }}/build/Install
      BUILD_PATH: ${{ github.workspace }}/build
      ARCHIVE_NAME: supercollider-gst-rtp-${{ matrix.name }}.zip

    steps:
    - name: Checkout GstRTP
      uses: actions/checkout@v2

    - name: Checkout SuperCollider
      uses: actions/checkout@v2
      with:
        repository: supercollider/supercollider
        path: ${{ env.SC_PATH }}
        ref: main

    - name: Download gstreamer (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y -f libopus0
        sudo apt-get install libunwind-dev
        sudo apt-get install -y -f gstreamer-1.0 gstreamer1.0-plugins-base libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      
    - name: Download gstreamer (macOS)
      if: runner.os == 'macOS'
      run: brew install gstreamer

      # Build
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory $BUILD_PATH

    - name: Configure CMake
      shell: bash
      working-directory: ${{ env.BUILD_PATH }}
      run: cmake .. -DCMAKE_BUILD_TYPE='Release' -DSC_PATH="$SC_PATH" -DCMAKE_INSTALL_PREFIX="$INSTALL_PATH"

    - name: Build
      shell: bash
      working-directory: ${{ env.BUILD_PATH }}
      env:
        CMAKE_BUILD_PARALLEL_LEVEL: 4
      run: cmake --build . --config "Release" --target install

      # Gather all files in a zip
    - name: Zip up build (Unix)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ${{ env.INSTALL_PATH }}
      run: zip -r "$ARCHIVE_NAME" "GstRTP"

      # Upload
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.INSTALL_PATH }}/${{ env.ARCHIVE_NAME }}
        prerelease: true
        body: ""
        tag: ${{ github.ref }}
